all: 
  vars:
    ansible user: centos
    ansible_ssh_private_key_file: ./ansible/id_rsa 
    #ansible_ssh_private_key: ${{ secrets.ID_RSA }}
  children:
    prod:
      hosts: leo.goutard.takima.cloud