---
# tasks file for roles/launch_database

# This task ensures that the app network exists using the docker_network module.
- name: Ensure app network exists
  docker_network:
    name: app-network

# This task runs the database container using the docker_container module.
- name: Run database container
  docker_container:
    name: my-postgres-container
    image: leogou/my-postgres-db:database-latest
    state: started
    restart_policy: always
    networks:
      - name: app-network
    ports:
      - "5432:5432"
