#- hosts: all
  #become: yes ## Yes I want to become a super user 
  #roles:
  #  - httpd
  #  - firewalld


#- hosts: all
#  gather_facts: false
#  become: true
#  tasks:
#   - name: Test connection
#     ping:

- hosts: all
  gather_facts: false
  become: true
  roles:
  - install_docker
  - create_network
  - launch_database
  - launch_app
  - launch_proxy
