name: Ansible

on:
  workflow_run:
    workflows: ["CI Build and Push Docker Image"]
    types:
      - completed
    branches: 
      - main

jobs:
  update-ansible:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Decrypt SSH key
        run: |
          echo "${{ secrets.ID_RSA }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
      - name: ansible
        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml