name: Ansible

on:
  workflow_run:
    workflows: ["CI Build and Push Docker Image"]
    types:
      - completed
    branches: 
      - main

#jobs:
#  update-ansible:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2.5.0
#      - name: ansible
#        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}

    - name: Adjust SSH key permissions
      run: chmod 600 ./ansible/id_rsa

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Disable host key checking
      run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

    - name: Run deployment playbook
      run: |
        ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False