name: Ansible  # Name of the GitHub Actions workflow

on:
  # Define the event that triggers this workflow
  workflow_run:
    workflows: ["CI Build and Push Docker Image"]  # Run this workflow when the specified workflow completes
    types:
      - completed  # Trigger when the specified workflow completes
    branches: 
      - main  # Trigger on pushes to the main branch

#jobs:
#  update-ansible:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2.5.0
#      - name: ansible
#        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Conditionally execute this job if the specified workflow completes successfully
    runs-on: ubuntu-latest  # Specify the operating system for the job

    steps:  # Define the steps to be executed in the job

      # Step 1: Checkout the GitHub repository code
      - name: Checkout repository
        uses: actions/checkout@v2  # Use the actions/checkout action to checkout the repository code

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3  # Use the webfactory/ssh-agent action to set up SSH
        with:
          ssh-private-key: ${{ secrets.ID_RSA }}  # Set the SSH private key from GitHub repository secrets

      # Step 3: Adjust SSH key permissions
      - name: Adjust SSH key permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 4: Debug SSH key
      - name: Debug SSH key
        run: |
          ls -l ~/.ssh
          cat ~/.ssh/id_rsa | head -c 100

      # Step 5: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible  # Install Ansible

      # Step 6: Disable host key checking
      - name: Disable host key checking
        run: echo "ANSIBLE_HOST_KEY_CHECKING=False" >> $GITHUB_ENV

      # Step 7: Run deployment playbook
      - name: Run deployment playbook
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml  # Run the Ansible playbook for deployment
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Set the ANSIBLE_HOST_KEY_CHECKING environment variable to False
