name: CI Build and Push Docker Image


on:
  workflow_run:
    workflows: ["CI devops 2024 / test-backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04



    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          context: ./API/simple-api-student-main
          tags: ${{ secrets.DOCKER_USERNAME }}/my-backend-app:backend-latest
          push: ${{ github.ref == 'refs/heads/main' }}
          #push: True

      - name: Build image and push database
        uses: docker/build-push-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/my-postgres-db:database-latest
          push: True
          #push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}        
        with:
          context: ./http
          tags: ${{ secrets.DOCKER_USERNAME }}/my-apache2:httpd-latest
          push: True
          #push: ${{ github.ref == 'refs/heads/main' }}